# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: sway-desktop
description: Immutable Fedora for ThinkPad  with Sway

# base-image: # the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 44 # latest is also supported if you want new updates ASAP


modules:

  - type: rpm-ostree
    repos:
    - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-44.noarch.rpm
    - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-44.noarch.rpm

    remove:
      - tuned-ppd
    install:
      - brightnessctl
      - brz                 
      - ccid
      - chromium
      - ffmpegthumbnailer
      - firefox
      - flac         
      - gutenprint   
      - id3lib       
      - id3v2        
      - iio-sensor-proxy
      - ImageMagick  
      - jq
      - keepassxc
      - libwacom
      - libwacom-utils
      - mosh                
      - mpg123       
      - nautilus
      - neomutt
      - nextcloud-client-nautilus
      - nmap
      - opensc
      - opus-tools   
      - pcsc-lite           
      - poppler-utils
      - pwgen               
      - remmina
      - remmina-plugins-rdp
      - rkhunter       
      - scdoc
      - screen 
      - sway 
      - swayidle 
      - swaylock 
      - testdisk            
      - texlive
      - tlp
      - tlp-rdw
      - unzip               
      - v4l-utils
      - vim
      - waybar  
      - xournalpp
      # - yazi
      - yubikey-manager
  
  - type: systemd
    system:
      enabled:
        - tlp.service
        - iio-sensor-proxy.service
        - pcscd.service 
  
  - type: default-flatpaks
    configurations:
      - scope: system
        notify: true
        repo:
          url: https://dl.flathub.org/repo/flathub.flatpakrepo
          name: flathub
          title: "Flathub (sys)"
        install:
          - org.videolan.VLC
          - org.telegram.desktop
          - org.signal.Signal
          - ch.threema.threema-web-desktop
          - com.obsproject.Studio
          
  - type: script
    snippets:
      - |
        set -eux
        ##################################################################
        # installing wvkdb
        ##################################################################
        echo "Installing build dependencies for wvkbd..."

        dnf install -v -y \
          cairo-devel \
          cargo \
          git \
          libinput-devel \
          libxkbcommon-devel \
          make \
          meson \
          ninja-build \
          gcc \
          glib2-devel \
          pango-devel \
          rust \       
          systemd-devel \
          wayland-devel 
          
        #echo "Cloning wvkbd..."

        #git clone --depth=1 https://github.com/jjsullivan5196/wvkbd.git /tmp/wvkbd
        #cd /tmp/wvkbd

        #echo "Building wvkbd..."

        #make

        #echo "Installing wvkbd..."

        #install -Dm755 wvkbd-mobintl /usr/bin/wvkbd-mobintl
        #ln -sf /usr/bin/wvkbd-mobintl /usr/bin/wvkbd


        ##################################################################
        # installing rot8
        ##################################################################
        echo "Installing rot8 dependencies..."

        echo "Cloning rot8..."

        #git clone --depth=1 https://github.com/efernau/rot8.git /tmp/rot8
        #cd /tmp/rot8

        #echo "Building rot8..."

        #cargo build --release
        
        #echo "Installing rot8..."
        
        #cp -av /tmp/rot8/target/release/rot8 /usr/bin/rot8
        #chmod 755 /usr/bin/rot8


        

        
